version: "3"

services:
  registry:
    image: registry:2
    hostname: registry
    ports:
      - 5000:5000
    networks:
      registry:
    volumes:
      - registry:/var/lib/registry
    restart: always

networks:
  registry:

volumes:
  registry:
